# Generated by Django 6.1.2 on 2026-10-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetailUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client", models.CharField(max_length=64)),
                ("county", models.SlugField(max_length=64)),
                ("day", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "detail usage",
                "verbose_name_plural": "detail usage",
                "indexes": [
                    models.Index(fields=["county", "day", "-count"], name="detail_usage_top")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("client", "county", "day"), name="detail_usage_once"
                    )
                ],
            },
        ),
    ]
